/*******************************************************************************
*
* NCrystal process component for the Union framework.
*
* %I
* Written by: NCrystal developers, converted to a Union component by Mads Bertelsen
* Date: 20.08.15
* Origin: NCrystal Developers (European Spallation Source ERIC and DTU Nutech)
*
* This file is part of NCrystal (see https://mctools.github.io/ncrystal/).
*
* Copyright 2015-2022 NCrystal developers
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*
* Original header text for NCrystal_sample.comp:
* McStas sample component for the NCrystal scattering library. Find more
* information at <a href="https://github.com/mctools/ncrystal/wiki">the NCrystal
* wiki</a>. In particular, browse the available datafiles at <a
* href="https://github.com/mctools/ncrystal/wiki/Data-library">Data-library</a>
* and read about format of the configuration string expected in the "cfg"
* parameter at <a
* href="https://github.com/mctools/ncrystal/wiki/Using-NCrystal">Using-NCrystal</a>.
*
* NCrystal is available under the <a
* href="http://www.apache.org/licenses/LICENSE-2.0">Apache 2.0 license</a>.
* Depending on the configuration choices, optional NCrystal modules under
* different licenses might be enabled - see <a
* href="https://github.com/mctools/ncrystal/wiki/About">About</a> for more
* details.
*
* %D
* This process uses the NCrystal library as a Union scattering process. It only
* provides physics; geometry and absorption are handled by the other Union
* components. Use Union_make_material to provide the absorption coefficient.
* Use Union_make_NCrystal_material for a complete material backed by one
* NCrystal configuration.
*
* %P
* INPUT PARAMETERS:
* cfg:               [str]    NCrystal material configuration string (details <a href="https://github.com/mctools/ncrystal/wiki/Using-NCrystal">on this page</a>).
* interact_fraction: [1]      How large a part of the scattering events should use this process 0-1 (sum of all processes in material = 1)
* init:              [string] Name of Union_init component (typically "init", default)
*
* %E
 *******************************************************************************/

DEFINE COMPONENT NCrystal_process

SETTING PARAMETERS(string cfg = "", interact_fraction=-1, string init="init")
DEPENDENCY "@NCRYSTALFLAGS@"

SHARE
%{
  #ifndef Union
  #error "The Union_init component must be included before this NCrystal_process component"
  #endif

  %include "union_ncrystal.c"
%}

DECLARE
%{
  struct NCrystal_physics_storage_struct NCrystal_storage;
  struct global_process_element_struct global_process_element;
  struct scattering_process_struct This_process;
  double NCrystal_convfact_ekin2vsq;
  double NCrystal_convfact_vsq2ekin;
  ncrystalsample_t_union params;

  #ifndef PROCESS_DETECTOR
  #define PROCESS_DETECTOR dummy
  #endif
%}

INITIALIZE
%{
  ncrystal_union_check_version (NAME_CURRENT_COMP);
  ncrystal_union_setup_conversion (&NCrystal_convfact_vsq2ekin, &NCrystal_convfact_ekin2vsq);
  memset (&params, 0, sizeof (params));
  ncrystal_union_setup_rng ();

  ncrystal_info_t info = ncrystal_create_info (cfg);
  double numberdensity = ncrystal_union_get_numberdensity (info, NAME_CURRENT_COMP);
  ncrystal_unref (&info);

  params.density_factor = 0.01 / numberdensity;
  params.inv_density_factor = 1.0 / params.density_factor;
  params.scat = ncrystal_create_scatter (cfg);
  params.proc_scat = ncrystal_cast_scat2proc (params.scat);
  params.proc_scat_isoriented = !ncrystal_isnonoriented (params.proc_scat);

  NCrystal_storage.stored_params = params;
  NCrystal_storage.ncrystal_convfact_vsq2ekin = NCrystal_convfact_vsq2ekin;
  NCrystal_storage.ncrystal_convfact_ekin2vsq = NCrystal_convfact_ekin2vsq;

  scattering_process_struct_init (&This_process);
  This_process.non_isotropic_rot_index = 1;
  This_process.needs_cross_section_focus = -1;
  This_process.eProcess = NCrystal;
  This_process.data_transfer.pointer_to_a_NCrystal_physics_storage_struct = &NCrystal_storage;
  This_process.probability_for_scattering_function = &NCrystal_physics_my;
  This_process.scattering_function = &NCrystal_physics_scattering;
  sprintf (This_process.name, "%s", NAME_CURRENT_COMP);
  This_process.process_p_interact = interact_fraction;
  rot_copy (This_process.rotation_matrix, ROT_A_CURRENT_COMP);

  sprintf (global_process_element.name, "%s", NAME_CURRENT_COMP);
  global_process_element.component_index = INDEX_CURRENT_COMP;
  global_process_element.p_scattering_process = &This_process;

  if (_getcomp_index (init) < 0) {
    fprintf (stderr, "NCrystal_process:%s: Error identifying Union_init component, %s is not a known component name.\n", NAME_CURRENT_COMP, init);
    exit (-1);
  }
  struct pointer_to_global_process_list* global_process_list = COMP_GETPAR3 (Union_init, init, global_process_list);
  add_element_to_process_list (global_process_list, global_process_element);
%}

TRACE
%{
%}

FINALLY
%{
  ncrystal_unref (&params.scat);
  ncrystal_invalidate (&params.proc_scat);
  if (params.absmode)
    ncrystal_unref (&params.proc_abs);
%}

END
